name: fraud_detector
description: Smart Monitoring Kit

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  fl_chart: ^0.66.0
  intl: ^0.19.0
  crypto: ^3.0.3
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

# App name
# (This is for reference, actual display name is set in AndroidManifest.xml and Info.plist)

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  image_path_android: "assets/images/app_icon.png"
  image_path_ios: "assets/images/app_icon.png"
  image_path_round: "assets/images/app_icon.png"


